# Generated by Django 3.2.12 on 2022-05-09 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fridges',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
    ]
