# Generated by Django 3.2.12 on 2022-05-09 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_ingredient_date_stocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.customer'),
        ),
    ]
