# Generated by Django 3.2.12 on 2022-05-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0004_ingredient_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.customer'),
        ),
    ]
