# Generated by Django 3.2.12 on 2022-05-09 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_alter_ingredient_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='date_stocked',
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_stocked', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.customer')),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pantry.ingredient')),
            ],
        ),
    ]
