# Generated by Django 3.2.12 on 2022-05-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_auto_20220509_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridge',
            name='ingredient',
            field=models.ManyToManyField(blank=True, to='pantry.Ingredient'),
        ),
    ]
